# Define a mapping of countries to their correct world regions
sa = "South Asia"
eca = "Europe and Central Asia"
mena = "Middle East and North Africa"
ssa = "Sub-Saharan Africa"
lac = "Latin America and Caribbean"
eap = "East Asia and Pacific"
na = "North America"
country_to_region = {
    "Afghanistan": sa,
    "Albania": eca,
    "Algeria": mena,
    "Andorra": eca,
    "Angola": ssa,
    "Antigua and Barbuda": lac,
    "Argentina": lac,
    "Armenia": eca,
    "Australia": eap,
    "Austria": eca,
    "Azerbaijan": eca,
    "Bahamas": lac,
    "Bahrain": mena,
    "Bangladesh": sa,
    "Barbados": lac,
    "Belarus": eca,
    "Belgium": eca,
    "Belize": lac,
    "Benin": ssa,
    "Bhutan": sa,
    "Bolivia": lac,
    "Bosnia and Herzegovina": eca,
    "Botswana": ssa,
    "Brazil": lac,
    "Brunei": eap,
    "Bulgaria": eca,
    "Burkina Faso": ssa,
    "Burundi": ssa,
    "Cabo Verde": ssa,
    "Cambodia": eap,
    "Cameroon": ssa,
    "Canada": na,
    "Central African Republic": ssa,
    "Chad": ssa,
    "Chile": lac,
    "China": eap,
    "Colombia": lac,
    "Comoros": ssa,
    "Congo (Congo-Brazzaville)": ssa,
    "Congo (Democratic Republic of the Congo)": ssa,
    "Costa Rica": lac,
    "Croatia": eca,
    "Cuba": lac,
    "Cyprus": eca,
    "Czech Republic": eca,
    "Denmark": eca,
    "Djibouti": ssa,
    "Dominica": lac,
    "Dominican Republic": lac,
    "Ecuador": lac,
    "Egypt": mena,
    "El Salvador": lac,
    "Equatorial Guinea": ssa,
    "Eritrea": ssa,
    "Estonia": eca,
    "Eswatini": ssa,
    "Ethiopia": ssa,
    "Fiji": eap,
    "Finland": eca,
    "France": eca,
    "Gabon": ssa,
    "Gambia": ssa,
    "Georgia": eca,
    "Germany": eca,
    "Ghana": ssa,
    "Greece": eca,
    "Grenada": lac,
    "Guatemala": lac,
    "Guinea": ssa,
    "Guinea-Bissau": ssa,
    "Guyana": lac,
    "Haiti": lac,
    "Honduras": lac,
    "Hungary": eca,
    "Iceland": eca,
    "India": sa,
    "Indonesia": eap,
    "Iran": mena,
    "Iraq": mena,
    "Ireland": eca,
    "Israel": mena,
    "Italy": eca,
    "Jamaica": lac,
    "Japan": eap,
    "Jordan": mena,
    "Kazakhstan": eca,
    "Kenya": ssa,
    "Kiribati": eap,
    "Korea (North)": eap,
    "Korea (South)": eap,
    "Kuwait": mena,
    "Kyrgyzstan": eca,
    "Laos": eap,
    "Latvia": eca,
    "Lebanon": mena,
    "Lesotho": ssa,
    "Liberia": ssa,
    "Libya": mena,
    "Liechtenstein": eca,
    "Lithuania": eca,
    "Luxembourg": eca,
    "Macedonia": eca,
    "Madagascar": ssa,
    "Malawi": ssa,
    "Malaysia": eap,
    "Maldives": sa,
    "Mali": ssa,
    "Malta": eca,
    "Marshall Islands": eap,
    "Mauritania": ssa,
    "Mauritius": ssa,
    "Mexico": lac,
    "Micronesia (Federated States of)": eap,
    "Moldova": eca,
    "Monaco": eca,
    "Mongolia": eap,
    "Montenegro": eca,
    "Morocco": mena,
    "Mozambique": ssa,
    "Myanmar (formerly Burma)": eap,
    "Namibia": ssa,
    "Nauru": eap,
    "Nepal": sa,
    "Netherlands": eca,
    "New Zealand": eap,
    "Nicaragua": lac,
    "Niger": ssa,
    "Nigeria": ssa,
    "North Macedonia": eca,
    "Norway": eca,
    "Oman": mena,
    "Pakistan": sa,
    "Palau": eap,
    "Panama": lac,
    "Papua New Guinea": eap,
    "Paraguay": lac,
    "Peru": lac,
    "Philippines": eap,
    "Poland": eca,
    "Portugal": eca,
    "Qatar": mena,
    "Romania": eca,
    "Russia": eca,
    "Rwanda": ssa,
    "Saint Kitts and Nevis": lac,
    "Saint Lucia": lac,
    "Saint Vincent and the Grenadines": lac,
    "Samoa": eap,
    "San Marino": eca,
    "Sao Tome and Principe": ssa,
    "Saudi Arabia": mena,
    "Senegal": ssa,
    "Serbia": eca,
    "Seychelles": ssa,
    "Sierra Leone": ssa,
    "Singapore": eap,
    "Slovakia": eca,
    "Slovenia": eca,
    "Solomon Islands": eap,
    "Somalia": ssa,
    "South Africa": ssa,
    "South Sudan": ssa,
    "Spain": eca,
    "Sri Lanka": sa,
    "Sudan": ssa,
    "Suriname": lac,
    "Sweden": eca,
    "Switzerland": eca,
    "Syria": mena,
    "Taiwan": eap,
    "Tajikistan": eca,
    "Tanzania": ssa,
    "Thailand": eap,
    "Timor-Leste": eap,
    "Togo": ssa,
    "Tonga": eap,
    "Trinidad and Tobago": lac,
    "Tunisia": mena,
    "Turkey": eca,
    "Turkmenistan": eca,
    "Tuvalu": eap,
    "Uganda": ssa,
    "Ukraine": eca,
    "United Arab Emirates": mena,
    "United Kingdom": eca,
    "United States": na,
    "Uruguay": lac,
    "Uzbekistan": eca,
    "Vanuatu": eap,
    "Venezuela": lac,
    "Vietnam": eap,
    "Yemen": mena,
    "Zambia": ssa,
    "Zimbabwe": ssa
}


# Read the full SQL file and process it line by line
updated_lines = []
with open("Addresses.sql", "r", encoding="utf-8") as file:
    for line in file:
        # Extract the country from the SQL statement
        for country, region in country_to_region.items():
            if f"'{country}'" in line:  # Check if the country is in the line
                # Replace the incorrect worldRegion value with the correct one
                line = line.replace(line.split(",")[8], f" '{region}'")  # Update worldRegion
                break  # Stop checking once a match is found
        updated_lines.append(line)

# Save the updated SQL file
updated_file_path = "./Updated_Addresses.sql"
with open(updated_file_path, "w", encoding="utf-8") as file:
    file.writelines(updated_lines)

# Return the path of the updated file
updated_file_path
