INSERT INTO [dbo].[Species] (id, [name]) VALUES (1,'Catfish')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (2,'Carp')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (3,'Trout')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (4,'Pike')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (5,'Perch')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (6,'Tilapia')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (7,'Sturgeon')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (8,'Guppy')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (9,'Tetra')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (10,'Tuna')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (11,'Mackerel')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (12,'Cod')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (13,'Snapper')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (14,'Grouper')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (15,'Halibut')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (16,'Flounder')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (17,'Marlin')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (18,'Swordfish')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (19,'Barracuda')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (20,'Great ')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (21,'Shark')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (22,'Tiger Shark')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (23,'Hammerhead')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (24,'Bull Shark')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (25,'Whale Shark')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (26,'Manta Ray')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (27,'Stingray')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (28,'Sawfish')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (29,'Clownfish')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (30,'Angelfish')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (31,'Parrotfish')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (32,'Butterflyfish')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (33,'Tang')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (34,'Wrasse')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (35,'Goby')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (36,'Mandarinfish')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (37,'Coelacanth')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (38,'Lungfish')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (39,'Paddlefish')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (40,'Archerfish')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (41,'Electric Eel')
INSERT INTO [dbo].[Species] (id, [name]) VALUES (42,'Arowana')
