USE [FishSellingDB]
GO

INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (1, 'Ocean', 'Large', 'The largest body of saltwater, covering most of the Earth''s surface.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (2, 'Sea', 'Large', 'A large saltwater body, smaller than an ocean, often partly enclosed by land.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (3, 'Gulf', 'Large', 'A large portion of the sea partially enclosed by land.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (4, 'Bay', 'Large', 'A broad inlet of the sea where the land curves inward.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (5, 'Sound', 'Large', 'A large sea or ocean inlet, often between two bodies of land.')

INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (6, 'Lake', 'Medium', 'A large inland body of water, usually freshwater, but some are saltwater.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (7, 'Lagoo', 'Medium', 'A shallow body of water separated from a larger body by a barrier (e.g., reefs).')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (8, 'Reservoir', 'Medium', 'A man-made lake used for storing water.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (9, 'Estuary', 'Medium', 'A coastal area where freshwater from rivers meets saltwater from the sea.')

INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (10, 'River', 'Large', 'A large, flowing body of freshwater that moves towards an ocean, sea, or lake.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (11, 'Stream', 'Small', 'A small, narrow river')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (12, 'Brook', 'Very Small', 'A very small, natural stream of water.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (13, 'Creek', 'Medium', 'A medium-sized stream, often smaller than a river but larger than a brook.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (14, 'Tributary', 'Medium', 'A smaller river or stream that flows into a larger one.')

INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (15, 'Pond', 'Small', 'A small, still body of water, usually smaller than a lake.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (16, 'Pool', 'Small', 'A small, still water body, can be natural or artificial.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (17, 'Spring', 'Small', 'A natural water source where groundwater flows to the surface.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (18, 'Oasis', 'Small', 'A water source in a desert, often surrounded by vegetation.')

INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (19, 'Fjord', 'Long', 'A long, deep sea inlet between cliffs, formed by glaciers.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (20, 'Marsh', 'Small', 'A wetland with soft, grassy vegetation and standing water.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (21, 'Swamp', 'Small', 'A wetland dominated by trees and standing or slow-moving water.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (22, 'Canal', 'Long', 'A man-made waterway for transportation or irrigation.')
INSERT INTO [dbo].[WaterBodyTypes] ([id],[typeName],[size],[description]) VALUES (23, 'Strait', 'Small', 'A narrow passage of water connecting two larger bodies of water.')


GO



INSERT INTO [dbo].[Species] ([name]) VALUES ('Catfish')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Carp')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Trout')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Pike')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Perch')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Tilapia')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Sturgeon')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Guppy')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Tetra')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Tuna')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Mackerel')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Cod')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Snapper')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Grouper')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Halibut')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Flounder')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Marlin')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Swordfish')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Barracuda')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Great ')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Shark')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Tiger Shark')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Hammerhead')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Bull Shark')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Whale Shark')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Manta Ray')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Stingray')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Sawfish')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Clownfish')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Angelfish')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Parrotfish')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Butterflyfish')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Tang')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Wrasse')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Goby')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Mandarinfish')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Coelacanth')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Lungfish')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Paddlefish')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Archerfish')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Electric Eel')
INSERT INTO [dbo].[Species] ([name]) VALUES ('Arowana')
